"""add_phase_1b_metadata_fields_to_sensor_tracker_deployment

Revision ID: 272c548c8d82
Revises: 3673aca3bf34
Create Date: 2025-12-09 15:16:32.844054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = '272c548c8d82'
down_revision: Union[str, Sequence[str], None] = '3673aca3bf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add Phase 1B metadata fields to sensor_tracker_deployments."""
    # Deployment details
    op.add_column('sensor_tracker_deployments', sa.Column('deployment_cruise', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('recovery_cruise', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('deployment_personnel', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('recovery_personnel', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('wmo_id', String(), nullable=True))
    
    # Publication and data access
    op.add_column('sensor_tracker_deployments', sa.Column('data_repository_link', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('metadata_link', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('publisher_name', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('publisher_email', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('publisher_url', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('publisher_country', String(), nullable=True))
    
    # Attribution
    op.add_column('sensor_tracker_deployments', sa.Column('creator_name', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('creator_email', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('creator_url', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('creator_sector', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('contributor_name', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('contributor_role', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('contributors_email', String(), nullable=True))
    
    # Program information
    op.add_column('sensor_tracker_deployments', sa.Column('program', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('site', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('sea_name', String(), nullable=True))
    
    # Technical details
    op.add_column('sensor_tracker_deployments', sa.Column('transmission_system', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('positioning_system', String(), nullable=True))
    op.add_column('sensor_tracker_deployments', sa.Column('references', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_tracker_deployments', 'references')
    op.drop_column('sensor_tracker_deployments', 'positioning_system')
    op.drop_column('sensor_tracker_deployments', 'transmission_system')
    op.drop_column('sensor_tracker_deployments', 'sea_name')
    op.drop_column('sensor_tracker_deployments', 'site')
    op.drop_column('sensor_tracker_deployments', 'program')
    op.drop_column('sensor_tracker_deployments', 'contributors_email')
    op.drop_column('sensor_tracker_deployments', 'contributor_role')
    op.drop_column('sensor_tracker_deployments', 'contributor_name')
    op.drop_column('sensor_tracker_deployments', 'creator_sector')
    op.drop_column('sensor_tracker_deployments', 'creator_url')
    op.drop_column('sensor_tracker_deployments', 'creator_email')
    op.drop_column('sensor_tracker_deployments', 'creator_name')
    op.drop_column('sensor_tracker_deployments', 'publisher_country')
    op.drop_column('sensor_tracker_deployments', 'publisher_url')
    op.drop_column('sensor_tracker_deployments', 'publisher_email')
    op.drop_column('sensor_tracker_deployments', 'publisher_name')
    op.drop_column('sensor_tracker_deployments', 'metadata_link')
    op.drop_column('sensor_tracker_deployments', 'data_repository_link')
    op.drop_column('sensor_tracker_deployments', 'wmo_id')
    op.drop_column('sensor_tracker_deployments', 'recovery_personnel')
    op.drop_column('sensor_tracker_deployments', 'deployment_personnel')
    op.drop_column('sensor_tracker_deployments', 'recovery_cruise')
    op.drop_column('sensor_tracker_deployments', 'deployment_cruise')
    # ### end Alembic commands ###
